config/routes.rb
Rails.application.routes.draw do
  
  get 'usuario_en_hogar_activations/edit'

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'account_activations/edit'

  root 'static_pages#home'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  get 'signup' => 'users#new'

  resources :users do

    resources :posts, only: [:show, :create, :destroy] do

      resources :comments, only: [:create, :destroy]

    end

  end

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :hogares, only: [:index, :show]
  resources :megustas, only: [:create, :destroy]
  resources :direcciones, only: [:new, :create]
  resources :direccion_activations, only: [:new, :create]

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
  validates :post, presence: true
  validates :user, presence: true
  validates :content, presence: true
  default_scope -> { order('created_at ASC') }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  	before_action :logged_in_user_permitido_en_hogar?
  	before_action :correct_user_for_deleting_comment, only: [:destroy]

  	def create

  		@post = Post.find(params[:post_id])
  		@comment = current_user.comments.build(create_params)
  		if @comment.save
		      flash[:success] = "Comentario ha sido publicado"
		      redirect_to user_post_path(@post.user.id, @post.id)
		else
			flash[:danger] = "Comentario no ha sido publicado. Este intento ha sido reportado"
			redirect_to user_post_path(@post.user.id, @post.id)
		end

  	end

  	def destroy

  		@comment = Comment.find(params[:id])
  		if @comment.destroy
  			flash[:danger] = "Comentario ha sido borrado"
			redirect_to user_post_path(@comment.post.user.id, @comment.post.id)
		end
  	end


  	private
       #Confirms the correct user.
	    def correct_user_for_deleting_comment
	      @comment = Comment.find(params[:id])
	      @user = @comment.user
	      redirect_to(login_url) unless current_user?(@user)
	    end

	    def create_params
	    	params.require(:comment).permit(:content).merge!(:post_id => params[:post_id])
	    end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="comment">
	<div>
		<div class="user"><%= link_to comment.user.name, user_path(comment.user) %>
			  <% if current_user?(comment.user) %>
    | <%= link_to "Eliminar", user_post_comment_path(comment.post.user, comment.post, comment), method: :delete,
                                  data: { confirm: "Estas seguro?" } %>
  <% end %>
	<br><small><%= time_ago_in_words(comment.created_at) %> atras.</small>
		</div>
		<div class="content"><%= comment.content %></div>
	</div>
</div>

app/views/comments/_comment_box.html.erb
<%= form_for :comment, url: user_post_comments_path(post.user.id, post.id) do |f| %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Publicar nuevo comentario..." %>
  </div>
  <%= f.submit "Comentar", class: "btn btn-primary" %>
<% end %>