config/routes.rb
Rails.application.routes.draw do
  
  get 'usuario_en_hogar_activations/edit'

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'account_activations/edit'

  root 'static_pages#home'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  get 'signup' => 'users#new'

  resources :users do

    resources :posts, only: [:show, :create, :destroy] do

      resources :comments, only: [:create, :destroy]

    end

  end

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :hogares, only: [:index, :show]
  resources :megustas, only: [:create, :destroy]
  resources :direcciones, only: [:new, :create]
  resources :direccion_activations, only: [:new, :create]

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_post_form.html.erb
<div class="post-form">
	<ul class="nav nav-tabs" role="tablist">
	<% @tags.each do |tag| %>
		<li <%= "class='active'".html_safe if tag == @tags.first %>><a href="#tab_<%= tag.slug %>" data-toggle="tab"><%= tag.name %></a></li>
	<% end %>
	</ul>
	<div class="tab-content">
		<% @tags.each do |tag| 

			if tag.name == @tags.first.name 

				@clase = "active" %>

				<%= render partial: "shared/post_form_#{tag.slug}", locals: { post: @post, clase: @clase } %>

			<% else %>

				<%= render partial: "shared/post_form_#{tag.slug}", locals: { post: @post, clase: "" } %>

			<% end %>

		 <% end %>
	</div>
</div>

app/views/shared/_post_form_convivencia.html.erb
<div class="tab-pane <%= clase %>" id="tab_convivencia">
	 <%= form_for post, url: user_posts_path(current_user.id, post.id) do |f| %>
			<%= render 'shared/error_messages', object: f.object %>
	    <div class="field">
	    <%= f.text_area :content, placeholder: "Escribe aquí para publicar nuevo mensaje..." %>
	    <%= f.hidden_field :tag, :value => :convivencia %>

	    </div>
	    <%= f.submit "Publicar!", class: "btn btn-primary" %>
	<% end %>
</div>

app/views/shared/_post_form_emergencia.html.erb
<div class="tab-pane <%= clase %>" id="tab_emergencia">
	 <%= form_for post, url: user_posts_path(current_user.id, post.id) do |f| %>
			<%= render 'shared/error_messages', object: f.object %>
	    <div class="field">
	    <%= f.text_area :content, placeholder: "Escribe aquí para publicar nuevo mensaje..." %>
	    <%= f.hidden_field :tag, :value => :emergencia %>

	    </div>
	    <%= f.submit "Publicar!", class: "btn btn-primary" %>
	<% end %>
</div>

app/views/shared/_post_form_limpieza.html.erb
<div class="tab-pane <%= clase %>" id="tab_limpieza">
	 <%= form_for post, url: user_posts_path(current_user.id, post.id) do |f| %>
			<%= render 'shared/error_messages', object: f.object %>
	    <div class="field">
	    <%= f.text_area :content, placeholder: "Escribe aquí para publicar nuevo mensaje..." %>
	    <%= f.hidden_field :tag, :value => :limpieza %>

	    </div>
	    <%= f.submit "Publicar!", class: "btn btn-primary" %>
	<% end %>
</div>

app/views/shared/_post_form_recomendacion_favor.html.erb
<div class="tab-pane <%= clase %>" id="tab_recomendacion_favor">
	 <%= form_for post, url: user_posts_path(current_user.id, post.id) do |f| %>
		<%= render 'shared/error_messages', object: f.object %>
	    <div class="field">
	    <%= f.text_area :content, placeholder: "Escribe aquí para publicar nuevo mensaje..." %>
	    <%= f.hidden_field :tag, :value => :recomendacion_favor %>
	    </div>
	    <%= f.submit "Publicar!", class: "btn btn-primary" %>
	<% end %>
</div>

app/views/shared/_post_form_seguridad.html.erb
<div class="tab-pane <%= clase %>" id="tab_seguridad">
	 <%= form_for post, url: user_posts_path(current_user.id, post.id) do |f| %>
		<%= render 'shared/error_messages', object: f.object %>
	    <div class="field">
	    <%= f.text_area :content, placeholder: "Escribe aquí para publicar nuevo mensaje...", class: "post-form-box post-form-box-seguridad" %>
	    <%= f.hidden_field :tag, :value => :seguridad %>
	    </div>
	    <%= f.submit "Publicar!", class: "btn btn-primary" %>
	<% end %>
</div>