config/routes.rb
Rails.application.routes.draw do
  
  get 'usuario_en_hogar_activations/edit'

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'account_activations/edit'

  root 'static_pages#home'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  get 'signup' => 'users#new'

  resources :users do

    resources :posts, only: [:show, :create, :destroy] do

      resources :comments, only: [:create, :destroy]

    end

  end

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :hogares, only: [:index, :show]
  resources :megustas, only: [:create, :destroy]
  resources :direcciones, only: [:new, :create]
  resources :direccion_activations, only: [:new, :create]

end

app/controllers/direccion_activations_controller.rb
class DireccionActivationsController < ApplicationController
	#Chequeamos que el usuario esté logueado
  before_action :logged_in_user
  before_action :usuario_con_hogar
  before_action :usuario_no_permitido_en_hogar
  before_action :direccion_no_activada
  before_action :usuario_es_administrador_del_hogar
	
  def new
  end

  def create



  	if current_user.hogar.direccion.authenticated?(:activation, activacion_params)
	  		
  			#activamos la direccion
  			current_user.hogar.direccion.activate
  			#permitimos al usuario en el hogar
  			current_user.activar_en_hogar
  			#Enviamos mensaje de que el usuario se ha activado
		      flash[:success] = "Tu direccion ha sido activada! Bienvenido a la red!"
		      redirect_to root_url
		    
		else

      
			flash[:success] = "Código incorrecto"
			render 'direccion_activations/new'

		end

  end

  private

  	def activacion_params

  		params[:direccion_activations].permit(:activation_code)[:activation_code]

  	end

    def direccion_no_activada

      unless !current_user.hogar.direccion.activated? 
        flash[:danger] = "Tu direccion ya está activada, no puedes hacerlo nuevamente"
        redirect_to root_url 
      end

    end

end

app/helpers/direccion_activations_helper.rb
module DireccionActivationsHelper
end

app/views/direccion_activations/create.html.erb
<h1>DireccionActivations#update</h1>
<p>Find me in app/views/direccion_activations/update.html.erb</p>

app/views/direccion_activations/new.html.erb
<div class="container">
	<h2>Porfavor, ingresa el código de activación</h2>
	<%= form_for :direccion_activations, url: direccion_activations_path do |f| %>

	<%= f.text_field :activation_code, placeholder: "Escribe aquí el código de activación" %>
	<%= f.submit "Activar mi usuario!", class: "btn btn-primary" %>
	<% end %>
</div>

app/views/direccion_activations/update.html.erb
<h1>DireccionActivations#update</h1>
<p>Find me in app/views/direccion_activations/update.html.erb</p>