config/routes.rb
Rails.application.routes.draw do
  
  get 'usuario_en_hogar_activations/edit'

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'account_activations/edit'

  root 'static_pages#home'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  get 'signup' => 'users#new'

  resources :users do

    resources :posts, only: [:show, :create, :destroy] do

      resources :comments, only: [:create, :destroy]

    end

  end

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :hogares, only: [:index, :show]
  resources :megustas, only: [:create, :destroy]
  resources :direcciones, only: [:new, :create]
  resources :direccion_activations, only: [:new, :create]

end

app/models/megusta.rb
class Megusta < ActiveRecord::Base
  belongs_to :post
  belongs_to :user

  validates :post, presence: true
  validates :user, presence: true

  validates_uniqueness_of :megusta, scope: [:post_id, :user_id]


end

app/controllers/megustas_controller.rb
class MegustasController < ApplicationController
	#before_ asegurarse que en destroy es el usuairo adecuado
	before_action :logged_in_user_permitido_en_hogar?
	before_action :current_user_can_only_delete_own_megustas, only: [:destroy]

  def create

  	@post = Post.find(post_params)
  	@megusta = Megusta.create(params_megusta_create)
  	if @megusta.save
  		flash[:success] = "El post ha sido marcado como que te gusta"
  		redirect_to root_path
  	else
  		flash[:error] = "El post no ha podido ser marcado como que te gusta"
  		redirect_to user_post_path(@post.user, @post)
  	end
  end

  def destroy

  	@megusta = Megusta.find(params[:id])

  	if @megusta.destroy
  		redirect_to root_path
  	else
  		flash[:error] = "No se ha podido quitar me gusta"
  		redirect_to login_path
  	end

  end


  private
	  def params_megusta_create

	  		params.require(:megusta).permit(:post_id).merge!(user_id: current_user.id)

	  end

	  def post_params
	  	params.require(:megusta).permit(:post_id)[:post_id]
	  end

	  def current_user_can_only_delete_own_megustas
	  	@megusta = Megusta.find(params[:id])
	  	redirect_to login_path unless current_user?(@megusta.user)
	  end
end

app/helpers/megusta_helper.rb
module MegustaHelper
end

app/views/megustas/_megusta.html.erb
<div class="megusta-personas padding-top">
  <div class="col-xs-12 col-md-4">
    <%
    @megusta = post.usuario_puso_me_gusta?(current_user)
    if @megusta %> 
    	<%= form_for :megusta, url: megusta_path(@megusta), html: { class: "form-inline" } , method: :delete do |f| %>
    		<%= f.hidden_field :post_id, :value => post.id %>
    		<%= f.submit "No me gusta", class: "btn btn-danger btn-nomegusta" %>
    	<% end %>
    <% else %>
    	<%= form_for :megusta, url: megustas_path do |f| %>
    		<%= f.hidden_field :post_id, :value => post.id %>
    		<%= f.submit "Me Gusta", class: "btn btn-success btn-megusta" %>
    	<% end %>
    <% end %>
  </div>
  <div class="col-xs-12 col-md-8">
  <%= render partial: 'megustas/personas_megusta', locals: { post: post } %>
  </div>
</div>

app/views/megustas/_personas_megusta.html.erb
<% if post.megustas.any? %>

  		A <% post.megustas.take(3).each do |megusta| %>
  			<%= link_to megusta.user.name, user_path(megusta.user) %>
  			<%= "," if (post.megustas.take(3).first == megusta && post.megustas.count > 2) || (post.megustas.take(2).last == megusta && post.megustas.count > 3)%>
  			<%= "y" if (post.megustas.take(2).last == megusta && post.megustas.count == 3) ||  (post.megustas.take(2).first == megusta && post.megustas.count == 2) %>
  			<% end %>
  		  <% if post.megustas.count > 3 %>
  				y <%= pluralize(post.megustas.count-3, "persona") %> más <%= "le".pluralize(post.megustas.count-3) %> gusta esto.
  		  <% else %>
  		  		<%= "le".pluralize(post.megustas.count) %> gusta esto.
  		  <% end %>

<% end %>